const $=s=>document.querySelector(s), api=async(path,opts={})=>{const r=await fetch("/api"+path,{...opts,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...opts.headers}});if(!r.ok){let e=await r.json().catch(()=>({error:"Request failed"}));throw Error(e.error)}return r.status===204?null:r.json()};
let token=localStorage.getItem("keyline-token"),mode="login",tasks=[];
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===b));$(".name-field").style.display=mode==="register"?"block":"none"});
$("#auth").onsubmit=async e=>{e.preventDefault();$("#auth-error").textContent="";try{const body={email:$("#email").value,password:$("#password").value,...(mode==="register"?{name:$("#name").value}:{})};const data=await api("/auth/"+mode,{method:"POST",body:JSON.stringify(body)});token=data.token;localStorage.setItem("keyline-token",token);openWorkspace(data.user)}catch(err){$("#auth-error").textContent=err.message}};
async function openWorkspace(user){try{user=user||await api("/me");$("#gate").hidden=true;$("#workspace").hidden=false;$("#username").textContent=user.name;$("#useremail").textContent=user.email;$("#firstname").textContent=user.name.split(" ")[0];$("#avatar").textContent=user.name[0].toUpperCase();const h=new Date().getHours();$("#daypart").textContent=h<12?"morning":h<18?"afternoon":"evening";tasks=await api("/tasks")||[];render()}catch{logout()}}
function render(){$("#remaining").textContent=tasks.filter(t=>!t.completed).length;$("#done").textContent=tasks.filter(t=>t.completed).length;$("#progress").style.width=(tasks.length?tasks.filter(t=>t.completed).length/tasks.length*100:0)+"%";$("#tasks").innerHTML=tasks.length?tasks.map(t=>`<div class="task ${t.completed?"done":""}"><input type="checkbox" ${t.completed?"checked":""} onchange="toggle('${t.id}',this.checked)"><p>${escapeHTML(t.title)}<small>${new Date(t.createdAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})} · secured item</small></p><button onclick="removeTask('${t.id}')">×</button></div>`).join(""):`<div class="empty">Your ledger is clear. Add the first thing on your mind.</div>`}
$("#new-task").onsubmit=async e=>{e.preventDefault();const input=e.currentTarget.querySelector("input");try{tasks.unshift(await api("/tasks",{method:"POST",body:JSON.stringify({title:input.value})}));input.value="";render();toast("Task securely stored")}catch(e){toast(e.message)}};
window.toggle=async(id,completed)=>{const updated=await api("/tasks/"+id,{method:"PATCH",body:JSON.stringify({completed})});tasks=tasks.map(t=>t.id===id?updated:t);render()};window.removeTask=async id=>{await api("/tasks/"+id,{method:"DELETE"});tasks=tasks.filter(t=>t.id!==id);render();toast("Task removed")};
function logout(){token=null;localStorage.removeItem("keyline-token");$("#gate").hidden=false;$("#workspace").hidden=true}$("#logout").onclick=logout;function toast(s){$("#toast").textContent=s;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)}function escapeHTML(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML}if(token)openWorkspace();
