const dialog=document.querySelector("#welcome"),nameInput=document.querySelector("#name"),messages=document.querySelector("#messages"),form=document.querySelector("#composer"),input=document.querySelector("#input"),statusEl=document.querySelector("#status"),statusBox=document.querySelector(".status"),people=document.querySelector("#people"),count=document.querySelector("#count"),emptyState=document.querySelector("#empty-state"),charCount=document.querySelector("#char-count");
let socket,myName=localStorage.getItem("signal-name")||"";
function esc(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML}
function connect(){socket=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}/ws?name=${encodeURIComponent(myName)}`);socket.onopen=()=>{statusEl.textContent="live";statusBox.classList.add("live")};socket.onclose=()=>{statusBox.classList.remove("live");if(location.hostname.endsWith("vercel.app")){statusEl.textContent="persistent host required";render({type:"system",text:"Vercel serves this interface, but live WebSockets require the local Go server or a persistent host."});return}statusEl.textContent="reconnecting";setTimeout(connect,1500)};socket.onmessage=e=>render(JSON.parse(e.data))}
function render(e){if(e.type==="presence"){count.textContent=e.users.length;people.innerHTML=e.users.length?e.users.map(n=>`<span class="person">${esc(n)}</span>`).join(""):`<span class="empty-person">The room is quiet.</span>`;return}emptyState?.remove();const el=document.createElement("div");if(e.type==="system"){el.className="system";el.textContent=e.text}else{el.className="message"+(e.user===myName?" mine":"");el.innerHTML=`<div class="avatar">${esc(e.user.slice(0,2))}</div><div><div class="meta">${esc(e.user)}<time>${esc(e.time)}</time></div><div class="bubble">${esc(e.text)}</div></div>`}messages.append(el);messages.scrollTop=messages.scrollHeight}
form.addEventListener("submit",e=>{e.preventDefault();if(input.value.trim()&&socket?.readyState===1){socket.send(JSON.stringify({text:input.value}));input.value="";charCount.textContent="0"}});
input.addEventListener("input",()=>charCount.textContent=input.value.length);
input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
document.querySelector("#enter").addEventListener("click",e=>{if(!nameInput.value.trim()){e.preventDefault();return}myName=nameInput.value.trim();localStorage.setItem("signal-name",myName);connect()});
if(myName)connect();else{dialog.showModal();nameInput.focus()}
